- hosts: serveurs 
  tasks: 
    - name: Installation de Lynx sur les serveurs  
      become: true 
      become_user: root 
      apt: 
        name: lynx 
        state: present 
        update_cache: true 
