- hosts: serveurs
  become: true
  become_user: root
  tasks:

    - name: Update les apt repository et la cache sur le serveurs Ubuntu
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 state=latest

    - name: Upgrade tous les packages dans les servers
      apt: upgrade=dist update_cache=yes force_apt_get=yes dpkg_options='force-confold,force-confdef'
    
    - name: Enleve les packages qui ne sont pas utiles dans la cache
      apt: autoclean=yes

    - name: Enleve les dependances qui ne sont plus necessaires
      apt: autoremove=yes

    - name: Check si un reboot est necessaire sur tous les servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot si cela est necessaire
      reboot:
        msg: "Reboot Active par Ansible pour le kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
